#!/usr/bin/env bash

# System/Exit menu for fuzzel

A=$(fuzzel --dmenu cat <<EOF
Toggle Theme
Lock
Logout
Reboot
Suspend
Shutdown
EOF
)

case "$A" in
    "Toggle Theme")
        current=$(gsettings get org.gnome.desktop.interface color-scheme)
        if [[ $current == "'prefer-dark'" ]]; then
            gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
        else
            gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
        fi
        ;;
    Lock) swaylock -f -c 000000 ;;
    Logout) swaymsg exit;;
    Reboot) systemctl reboot ;;
    Suspend) systemctl suspend ;;
    Shutdown) systemctl -i poweroff ;;
esac

exit 0
